language: python
python:
- '3.4'
- '3.5'
- '3.6'
matrix:
  include:
  - python: '3.7'
    dist: xenial
    sudo: true
install:
- pip install codecov
- pip install mypy
- if [ $(bc <<< "$TRAVIS_PYTHON_VERSION < 3.5") -eq 1 ]; then pip install typing; fi
script:
- python -m unittest discover .
- coverage run -m unittest discover .
- mypy cpyfunctional/
after_success:
- codecov
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  user: 3mp3ri0r
  password:
    secure:
  skip_existing: true
  on:
    branch: release
    tags: false
- provider: pypi
  distributions: sdist bdist_wheel
  user: 3mp3ri0r
  password:
    secure:
  skip_existing: true
  on:
    branch: master
    tags: true
